---
- hosts: web
  remote_user: root

  roles:
    - outils
    - github


  # tasks:
  #
  # - name: Envoi du clone GitHub
  #   git: >
  #     dest=var/www/cloud-projet
  #     repo="https://github.com/baptistechampmartin/cloud-project/tree/master/site-php"
  #     update=no


...
